name: github workflow
on: 
  - workflow_dispatch
  - push
jobs:
  actions-usecase:
    runs-on: ubuntu-latest
    steps:
      - name: checkoout the code
        uses: actions/checkout@v4
      - name: Print index.html
        run: cat index.html
