name: hello world
on: 
  push: # ["push", "workflow_dispatch"]
    branches:
      - main
      - '*ravi*'
  workflow_dispatch:
    branches:
      - main
  pull_request:
    types:
     - closed
     - opened
    branches:
      - main
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello multiline step
        run: |
          echo "Welcome to the world"
          echo "I am your guide"
  secondJob:
    runs-on: ubuntu-latest
    needs: hello
    steps:
      - name: Ravi
        run: echo "This is a beautiful world"
  variablePrint:
    runs-on: ubuntu-latest
    steps:
      - name: printing the variable value
        run: echo "value is: ${{ FIRSTVARIABLE }}"
