name: hello world
on: workflow_dispatch
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello step
        run: |
        echo "Welcome to the world"
        echo "I am your guide"
        
