name: if-demo
on: 
  push:
    branches:
      - main
      - develop
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Run if branch is main
        if: github.ref_name == 'main' # github.ref == 'refs/heads/main'
        run: echo "Running this for main step"
      - name: Run without condition
        run: echo "Running this for main step"
      - name: run for RaviBattula747 or chandra747
        if: github.actor == 'ravibatula747' || github.actor == 'chandra747'
        run: echo "It is triggered by either ravibattula747 or chandra747"
