name: if-demo
on: 
  push:
    branches:
      - main
      - develop
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Run if branch is main
        if: github.ref_name == 'main' # github.ref == 'refs/heads/main'
        run: echo "Running this for main step"
      - name: Run without condition
        run: echo "Running this for main step"
      - name: run for RaviBattula747 or chandra747
        if: github.actor == 'ravibattula747' || github.actor == 'chandra747'
        run: echo "It is triggered by either ravibattula747 or chandra747"
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main'
    steps:
      - name: deciding the execution based on the type
        run: echo "building the application"
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref_name == 'main'
    steps:
      - name: deploy step
        run: echo "deploying the application"

  qualityChecks:
    runs-on: ubuntu-latest
    if: startsWith(github.ref_name, 'feature') && github.event_name == 'push'
    steps:
      - name: perform code quality
        run: echo "Performing code quality to the code"
  devDeploy:
    runs-on: ubuntu-latest
    if: github.ref_name == 'develop' && github.event_name == 'push'
    steps:
      - name: dev deploy
        run: echo "deploying the code to deployment environment"
  prdDeploy:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main' && github.event_name == 'push'
    steps:
      - name: prod deploy
        run:  |
          echo "deploying the code to production environment"
          exit 1  # for failur test case
  SuccessNotify:
    runs-on: ubuntu-latest
    needs: ['qualityChecks','devDeploy','prdDeploy']
    if: always() && !failure()
    steps:
      - name: Notify success
        run: echo "Execution successful"
  failureNotify:
    runs-on: ubuntu-latest
    needs: ['qualityChecks','devDeploy','prdDeploy']
    if: failure()
    steps:
      - name: Notify failure
        run: |
          echo "Execution failed"
